04:51:21 PM: ERROR [conexion.py]: 28 - Error al conextar a la base de datos: type object 'Conexion' has no attribute '_Conexion__USER'
04:52:13 PM: ERROR [conexion.py]: 28 - Error al conectar a la base de datos: type object 'Conexion' has no attribute '_Conexion__USER'
04:52:42 PM: ERROR [conexion.py]: 28 - Error al conectar a la base de datos: type object 'Conexion' has no attribute '_Conexion__USER'
04:54:10 PM: ERROR [conexion.py]: 28 - Error al conectar a la base de datos: type object 'Conexion' has no attribute '_Conexion__USER'
04:54:15 PM: ERROR [conexion.py]: 28 - Error al conectar a la base de datos: type object 'Conexion' has no attribute '_Conexion__USER'
04:55:04 PM: ERROR [conexion.py]: 28 - Error al conectar a la base de datos: 
04:59:25 PM: ERROR [conexion.py]: 28 - Error al conectar a la base de datos: 
05:01:19 PM: ERROR [conexion.py]: 28 - Error al conectar a la base de datos: 
05:02:28 PM: INFO [conexion.py]: 28 - Error al conectar a la base de datos: 
05:02:41 PM: ERROR [conexion.py]: 28 - Error al conectar a la base de datos: 
05:03:10 PM: ERROR [conexion.py]: 28 - Error al conectar a la base de datos: type object 'Conexion' has no attribute 'conexion'
05:03:25 PM: ERROR [conexion.py]: 28 - Error al conectar a la base de datos: 
05:06:21 PM: ERROR [conec.py]: 26 - Error al conectar a la BD: 
05:07:06 PM: ERROR [conec.py]: 26 - Error al conectar a la BD: 
05:07:22 PM: ERROR [conec.py]: 39 - Error al obtener cursor:'OperationalError' object has no attribute 'message'
05:07:32 PM: ERROR [conec.py]: 26 - Error al conectar a la BD: 
05:19:19 PM: ERROR [conexion.py]: 29 - Error al conectar a la BD: 
05:19:19 PM: INFO [conexion.py]: 35 - None
05:19:42 PM: ERROR [conexion.py]: 28 - Error al conectar a la BD: 
05:19:42 PM: INFO [conexion.py]: 34 - None
05:21:17 PM: ERROR [conec.py]: 26 - Error al conectar a la BD: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 57211?

05:21:29 PM: ERROR [conec.py]: 26 - Error al conectar a la BD: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 57311?

05:21:50 PM: ERROR [conec.py]: 26 - Error al conectar a la BD: 
05:22:07 PM: ERROR [conec.py]: 38 - Error al obtener cursor:'NoneType' object has no attribute 'cursor'
05:22:48 PM: INFO [conec.py]: 58 - None
05:22:48 PM: DEBUG [conec.py]: 55 - Se han cerrado los objetos de conexión y cursor
05:23:12 PM: ERROR [conec.py]: 26 - Error al conectar a la BD: 
05:29:59 PM: INFO [conec.py]: 26 - <bound method Conexion.obtenerConexion of <class '__main__.Conexion'>>
05:31:26 PM: INFO [conec.py]: 28 - None
05:31:58 PM: INFO [conec.py]: 28 - None
05:33:03 PM: INFO [conec.py]: 28 - None
05:33:31 PM: INFO [conec.py]: 28 - None
05:43:00 PM: ERROR [conexion.py]: 26 - Error al conectar a la BD: 
05:43:37 PM: ERROR [conexion.py]: 26 - Error al conectar a la BD: 
05:43:49 PM: ERROR [conexion.py]: 26 - Error al conectar a la BD: type object 'Conexion' has no attribute 'conexion'
05:44:21 PM: ERROR [conexion.py]: 26 - Error al conectar a la BD: 
05:45:14 PM: ERROR [conexion.py]: 22 - Error al conectar a la BD: invalid dsn: invalid connection option "database"

05:46:00 PM: ERROR [conexion.py]: 22 - Error al conectar a la BD: invalid dsn: invalid connection option "database"

05:46:10 PM: ERROR [conexion.py]: 22 - Error al conectar a la BD: invalid dsn: invalid connection option "database"

05:46:17 PM: ERROR [conexion.py]: 22 - Error al conectar a la BD: invalid dsn: invalid connection option "database"

05:46:46 PM: ERROR [conexion.py]: 22 - Error al conectar a la BD: could not match 2 port numbers to 1 hosts

05:47:10 PM: ERROR [conexion.py]: 22 - Error al conectar a la BD: invalid port number: "cls.__DB_PORT"
invalid port number: "cls.__DB_PORT"

05:47:38 PM: ERROR [conexion.py]: 22 - Error al conectar a la BD: invalid port number: "cls.__DB_PORT"
invalid port number: "cls.__DB_PORT"

05:48:00 PM: ERROR [conexion.py]: 22 - Error al conectar a la BD: invalid port number: "cls.__DB_PORT"
invalid port number: "cls.__DB_PORT"

05:48:43 PM: ERROR [conexion.py]: 22 - Error al conectar a la BD: 
05:54:30 PM: ERROR [conexion.py]: 27 - Error al conectar a la BD: 
07:33:04 PM: ERROR [conexion.py]: 27 - Error al conectar a la BD: type object 'Conexion' has no attribute 'conexion'
07:33:30 PM: ERROR [conexion.py]: 27 - Error al conectar a la BD: type object 'Conexion' has no attribute 'conexion'
07:34:55 PM: DEBUG [conexion.py]: 24 - Conexion exitosa: <connection object at 0x032EC748; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
07:34:55 PM: INFO [conexion.py]: 33 - <connection object at 0x032EC748; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:01:50 PM: DEBUG [conexion.py]: 24 - Conexion exitosa: <connection object at 0x036AC748; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:01:50 PM: INFO [conexion.py]: 33 - <connection object at 0x036AC748; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:03:54 PM: ERROR [conexion.py]: 31 - Error al conectar a la BD: 
08:04:24 PM: ERROR [conexion.py]: 31 - Error al conectar a la BD: 
08:04:30 PM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x03164748; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:04:30 PM: INFO [conexion.py]: 38 - <connection object at 0x03164748; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:07:54 PM: ERROR [conexion.py]: 45 - Error al obtener el cursor: maximum recursion depth exceeded
08:07:56 PM: ERROR [conexion.py]: 45 - Error al obtener el cursor: maximum recursion depth exceeded
08:08:24 PM: ERROR [conexion.py]: 46 - Error al obtener el cursor: maximum recursion depth exceeded
08:08:54 PM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x034B0748; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:08:54 PM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x01CDD928; closed: 0>
08:08:54 PM: INFO [conexion.py]: 52 - <cursor object at 0x01CDD928; closed: 0>
08:13:55 PM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x033E1748; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:13:55 PM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x033B0928; closed: 0>
08:13:55 PM: INFO [conexion.py]: 66 - <cursor object at 0x033B0928; closed: 0>
08:13:55 PM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
08:24:58 PM: DEBUG [persona.py]: 15 - Id Persona: 1 - Nombre: lautaro - Apellido: fernandez - Email: email
01:33:00 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x03A9FB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
01:33:00 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x03A92B28; closed: 0>
01:33:00 AM: DEBUG [persona_dao.py]: 16 - b'SELECT * FROM persona ORDER BY id_persona'
01:33:00 AM: INFO [persona_dao.py]: 19 - [(1, 'lautaro', 'alegria', 'la@mail.com'), (2, 'ana', 'fernandez', 'af@mail.com')]
01:33:15 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x032AEB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
01:33:15 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x032A2BA8; closed: 0>
01:33:15 AM: DEBUG [persona_dao.py]: 16 - b'SELECT * FROM persona ORDER BY id_persona'
01:34:52 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x03BCFB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
01:34:52 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x03BC2B28; closed: 0>
01:34:52 AM: DEBUG [persona_dao.py]: 16 - b'SELECT * FROM persona ORDER BY id_persona'
01:34:52 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
01:44:25 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x032AEB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
01:44:25 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x032A3B28; closed: 0>
01:44:25 AM: DEBUG [persona_dao.py]: 33 - b'INSERT INTO persona(nombre, apellido, email) VALUES (%s,%s,%s)'
01:44:25 AM: DEBUG [persona_dao.py]: 34 - Persona a insertar: Id Persona: None - Nombre: Javier - Apellido: Sanchez - Email: jz@mail.com
01:44:25 AM: ERROR [persona_dao.py]: 44 - Error al insertar persona: 'Persona' object is not subscriptable
01:44:25 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
01:44:25 AM: DEBUG [persona_dao.py]: 52 - Registros insertados: None
01:45:44 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x0383EB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
01:45:44 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x03833B28; closed: 0>
01:45:44 AM: DEBUG [persona_dao.py]: 33 - b'INSERT INTO persona(nombre, apellido, email) VALUES (%s,%s,%s)'
01:45:44 AM: DEBUG [persona_dao.py]: 34 - Persona a insertar: Id Persona: None - Nombre: Javier - Apellido: Sanchez - Email: jz@mail.com
01:45:44 AM: ERROR [persona_dao.py]: 45 - Error al insertar persona: 'Persona' object is not subscriptable
01:45:44 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
01:45:44 AM: DEBUG [persona_dao.py]: 53 - Registros insertados: None
01:48:37 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x0307EB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
01:48:37 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x03070B28; closed: 0>
01:48:37 AM: DEBUG [persona_dao.py]: 33 - b'INSERT INTO persona(nombre, apellido, email) VALUES (%s,%s,%s)'
01:48:37 AM: DEBUG [persona_dao.py]: 34 - Persona a insertar: Id Persona: None - Nombre: Javier - Apellido: Sanchez - Email: jz@mail.com
01:48:37 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
01:48:37 AM: DEBUG [persona_dao.py]: 53 - Registros insertados: 1
01:51:09 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x018FFB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
01:51:09 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x018F3B28; closed: 0>
01:51:09 AM: DEBUG [persona_dao.py]: 33 - INSERT INTO persona(nombre, apellido, email) VALUES (%s,%s,%s)
01:51:09 AM: DEBUG [persona_dao.py]: 34 - Persona a insertar: Id Persona: None - Nombre: Javier - Apellido: Sanchez - Email: jz@mail.com
01:51:09 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
01:51:09 AM: DEBUG [persona_dao.py]: 53 - Registros insertados: 1
01:51:18 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x03B9FB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
01:51:18 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x03B93B28; closed: 0>
01:51:18 AM: DEBUG [persona_dao.py]: 33 - b'INSERT INTO persona(nombre, apellido, email) VALUES (%s,%s,%s)'
01:51:18 AM: DEBUG [persona_dao.py]: 34 - Persona a insertar: Id Persona: None - Nombre: Javier - Apellido: Sanchez - Email: jz@mail.com
01:51:18 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
01:51:18 AM: DEBUG [persona_dao.py]: 53 - Registros insertados: 1
02:17:08 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x0333DB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:17:08 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x0332FBA8; closed: 0>
02:17:08 AM: DEBUG [persona_dao.py]: 58 - b'UPDATE persona SET nombre=%s, apellido=%s, email=%s WHERE id_persona = %s'
02:17:08 AM: DEBUG [persona_dao.py]: 59 - Persona a actualizar: Id Persona: 3 - Nombre: Jorge - Apellido: Sanchez - Email: jz@mail.com
02:17:08 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
02:17:08 AM: DEBUG [persona_dao.py]: 107 - Registros insertados: 1
02:18:01 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x02F90B70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:18:01 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x02F82BA8; closed: 0>
02:18:01 AM: DEBUG [persona_dao.py]: 81 - b'DELETE FROM persona WHERE id_persona = %s'
02:18:01 AM: DEBUG [persona_dao.py]: 82 - Persona a eliminar: Id Persona: 3 - Nombre: Javier - Apellido: Sanchez - Email: jz@mail.com
02:18:01 AM: ERROR [persona_dao.py]: 93 - Error al insertar persona: type object 'PersonaDao' has no attribute 'cls'
02:18:01 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
02:18:01 AM: DEBUG [persona_dao.py]: 111 - Registros insertados: None
02:18:42 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x03D80B70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:18:42 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x03D72BA8; closed: 0>
02:18:42 AM: DEBUG [persona_dao.py]: 81 - b'DELETE FROM persona WHERE id_persona = %s'
02:18:42 AM: DEBUG [persona_dao.py]: 82 - Persona a eliminar: Id Persona: 3 - Nombre: Javier - Apellido: Sanchez - Email: jz@mail.com
02:18:42 AM: ERROR [persona_dao.py]: 93 - Error al eliminar persona: type object 'PersonaDao' has no attribute 'cls'
02:18:42 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
02:18:42 AM: DEBUG [persona_dao.py]: 111 - Registros insertados: None
02:19:04 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x03310B70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:19:04 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x03302BA8; closed: 0>
02:19:04 AM: DEBUG [persona_dao.py]: 81 - b'DELETE FROM persona WHERE id_persona = %s'
02:19:04 AM: DEBUG [persona_dao.py]: 82 - Persona a eliminar: Id Persona: 3 - Nombre: Javier - Apellido: Sanchez - Email: jz@mail.com
02:19:04 AM: ERROR [persona_dao.py]: 93 - Error al eliminar persona: type object 'PersonaDao' has no attribute 'cls'
02:19:04 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
02:19:04 AM: DEBUG [persona_dao.py]: 111 - Registros insertados: None
02:21:40 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x03D10B70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:21:40 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x03D04B28; closed: 0>
02:21:40 AM: DEBUG [persona_dao.py]: 81 - b'DELETE FROM persona WHERE id_persona = %s'
02:21:40 AM: DEBUG [persona_dao.py]: 82 - Persona a eliminar: Id Persona: 1 - Nombre: None - Apellido: None - Email: None
02:21:40 AM: ERROR [persona_dao.py]: 93 - Error al eliminar persona: type object 'PersonaDao' has no attribute 'cls'
02:21:40 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
02:21:40 AM: DEBUG [persona_dao.py]: 111 - Registros insertados: None
02:22:03 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x03C60B70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:22:03 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x03C54B28; closed: 0>
02:22:03 AM: DEBUG [persona_dao.py]: 81 - b'DELETE FROM persona WHERE id_persona = %s'
02:22:03 AM: DEBUG [persona_dao.py]: 82 - Persona a eliminar: Id Persona: 1 - Nombre: None - Apellido: None - Email: None
02:22:03 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
02:22:03 AM: DEBUG [persona_dao.py]: 111 - Registros insertados: 1
02:23:11 AM: DEBUG [conexion.py]: 26 - Conexion exitosa: <connection object at 0x02E60B70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:23:11 AM: DEBUG [conexion.py]: 43 - Se abrio el cursor con exito: <cursor object at 0x02E52B28; closed: 0>
02:23:11 AM: DEBUG [persona_dao.py]: 19 - b'SELECT * FROM persona ORDER BY id_persona'
02:23:11 AM: DEBUG [conexion.py]: 63 - Se han cerrado los objetos.
02:23:11 AM: DEBUG [persona_dao.py]: 103 - Id Persona: 2 - Nombre: ana - Apellido: fernandez - Email: af@mail.com
02:23:11 AM: DEBUG [persona_dao.py]: 103 - Id Persona: 3 - Nombre: Jorge - Apellido: Sanchez - Email: jz@mail.com
02:23:11 AM: DEBUG [persona_dao.py]: 103 - Id Persona: 4 - Nombre: Javier - Apellido: Sanchez - Email: jz@mail.com
02:23:11 AM: DEBUG [persona_dao.py]: 103 - Id Persona: 5 - Nombre: Javier - Apellido: Sanchez - Email: jz@mail.com
