07:51:19 PM: ERROR [conexion.py]: 27 - Error al conectar a la BD: 
07:52:20 PM: ERROR [conexion.py]: 27 - Error al conectar a la BD: 
07:52:22 PM: ERROR [conexion.py]: 27 - Error al conectar a la BD: 
07:52:24 PM: ERROR [conexion.py]: 27 - Error al conectar a la BD: 
08:17:56 PM: ERROR [conexion.py]: 27 - Error al conectar a la BD: 
08:21:37 PM: DEBUG [conexion.py]: 24 - Conexion exitosa: <connection object at 0x03D0BB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
08:21:37 PM: INFO [conexion.py]: 33 - <connection object at 0x03D0BB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
01:09:24 AM: DEBUG [conexion.py]: 24 - Conexion exitosa: <connection object at 0x03B2BB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
01:09:24 AM: INFO [conexion.py]: 33 - <connection object at 0x03B2BB70; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
